# Generated by Django 4.0.2 on 2022-05-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('company_name', models.CharField(max_length=30, verbose_name='company_name')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('street', models.CharField(max_length=20, verbose_name='street')),
                ('street_number', models.IntegerField()),
                ('postcode', models.CharField(max_length=6, verbose_name='postcode')),
                ('suite_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('social_links', models.URLField(null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25, verbose_name='username')),
                ('position', models.CharField(max_length=20, verbose_name='position')),
                ('min_salary', models.IntegerField(blank=True)),
                ('max_salary', models.IntegerField(blank=True)),
                ('remote', models.BooleanField()),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('cv', models.FileField(upload_to='uploads/')),
                ('social_links', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=50, verbose_name='response')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Offers.offer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Offers.user')),
            ],
        ),
    ]
