# Generated by Django 4.0.2 on 2022-05-25 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Offers.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='suite_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Offers.company'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
