# Generated by Django 4.0.4 on 2022-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='position',
            field=models.CharField(max_length=20, verbose_name='position'),
        ),
    ]
