# Generated by Django 4.0.4 on 2022-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0005_remove_company_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='suite_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
