# Generated by Django 4.0.4 on 2022-05-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0006_alter_company_suite_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Offers.company'),
        ),
    ]
