# Generated by Django 4.0.4 on 2022-05-27 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offers', '0009_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='response',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=None, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=None, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, max_length=2000, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default=None, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
