# Generated by Django 4.0.4 on 2022-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0010_remove_application_response_remove_application_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='reason'),
        ),
    ]
