# Generated by Django 4.0.4 on 2022-05-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0011_alter_application_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Offers.offer'),
        ),
    ]
