# Generated by Django 4.0.4 on 2022-06-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0018_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offers.offer'),
        ),
    ]
